// Generated by CoffeeScript 1.8.0
(function() {
  var saveOptions;

  saveOptions = function() {
    var $el, el, options, _i, _len, _ref;
    options = {};
    _ref = $('textarea, select, [type="hidden"], [type="password"], [type="text"], [type="radio"]:checked, [type="checkbox"]:checked');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      el = _ref[_i];
      $el = $(el);
      options[$el.attr('name')] = $el.val();
    }
    return options;
  };

  $(function() {
    var $el, hash, key, obj, val, _results;
    $("#b-cancel").on('click', function(e) {
      return document.location = "pebblejs://close";
    });
    $("#b-submit").on('click', function(e) {
      return document.location = "pebblejs://close#" + encodeURIComponent(JSON.stringify(saveOptions()));
    });
    hash = window.location.hash.substring(1);
    if (hash) {
      obj = jQuery.parseJSON(decodeURIComponent(hash));
      _results = [];
      for (key in obj) {
        val = obj[key];
        $el = $("[name=" + key + "]");
        _results.push($el.val(val));
      }
      return _results;
    }
  });

}).call(this);
